#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install -y haproxy=1.6.\*
# enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
config="\nfrontend node-http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver 16453-web-01 44.192.13.122:80 check\n\tserver 16453-web-02 44.210.106.28:80 check\n\n"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
