#!/usr/bin/env bash
# Installs firewall; block all incoming except 22, 443, 80

sudo apt-get update -y
sudp apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw reload
sudo ufw enable
