#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user

# update nginx config file with user nginx
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# change permissions and ownership of config file
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# update nginx to listen to port 8080
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

pkill apache2
sudo -u nginx service nginx restart
